version: 4.1.pre.{build}
clone_folder: c:\pillow
init:
- ECHO %PYTHON%
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# Uncomment previous line to get RDP access during the build. 


environment:
  X64_EXT: -x64
  matrix:
  - PYTHON: C:/Python27-x64
  - PYTHON: C:/Python34
  - PYTHON: C:/Python27
  - PYTHON: C:/Python34-x64
  - PYTHON: C:/Python33
  - PYTHON: C:/Python33-x64

install:
- git clone https://github.com/python-pillow/pillow-depends.git c:\pillow-depends
- xcopy c:\pillow-depends\*.zip c:\pillow\winbuild\
- xcopy c:\pillow-depends\*.tar.gz c:\pillow\winbuild\
- xcopy /s c:\pillow-depends\test_images\* c:\pillow\tests\images
- cd c:\pillow\winbuild\
- c:\python34\python.exe c:\pillow\winbuild\build_dep.py
- c:\pillow\winbuild\build_deps.cmd

build_script:
- '%PYTHON%\Scripts\pip.exe install pillow' 

test_script:
- "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" /p /enable python.exe /full
- cd c:\pillow
- '%PYTHON%\Scripts\pip.exe install nose'
- '%PYTHON%\python.exe test-installed.py -v -s'

matrix:
  fast_finish: true

# Uncomment the following line to get RDP access after the build/test and block for
# up to the timeout limit (~1hr)
#
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
